name: 'mcauth'
version: '3.0.0'
author: 'Dylan Hackworth'
main: 'dev.dylhack.mcauth.MCAuthMain'
api-version: '1.15'
commands:
  addalt:
    description: Add an alt account
    usage: /addalt <PlayerName>
  remalt:
    description: Remove an alt account
    usage: /remalt <PlayerName>
  getalts:
    description: List alt accounts of a person
    usage: /getalts <PlayerName>
  listalts:
    description: List all the alt accounts
    usage: /listalts
